name: Automatic Market Analysis

on:
  workflow_dispatch:  # 수동 실행 가능
  schedule:
    - cron: '0 14 * * 1-5'  # 월-금 오후 11시 (한국 시간, UTC+9)

jobs:
  analyze-market:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Market Analysis
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_FEEDBACK_DB_ID: ${{ secrets.NOTION_FEEDBACK_DB_ID }}
          NOTION_REPORT_DB_ID: ${{ secrets.NOTION_REPORT_DB_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python advanced_market_analyzer.py

      - name: Upload logs (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: analysis-logs
          path: |
            *.log
          retention-days: 7
